In [108]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd().parent

RAW_DATA = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"

PROCESSED_DATA.mkdir(exist_ok=True)

In [109]:
nav_history = pd.read_csv(RAW_DATA / "nav_history.csv")

transactions = pd.read_csv(RAW_DATA / "investor_transactions.csv")

performance = pd.read_csv(RAW_DATA / "scheme_performance.csv")

In [110]:
print(nav_history.info())

print(transactions.info())

print(performance.info())

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB
None

In [111]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [112]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [113]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [114]:
nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [115]:
# Convert date column to datetime
nav_history["date"] = pd.to_datetime(nav_history["date"])

print(nav_history.dtypes)

amfi_code             int64
date         datetime64[us]
nav                 float64
dtype: object

In [116]:
nav_history = nav_history.sort_values(
    by=["amfi_code", "date"]
).reset_index(drop=True)

nav_history.head()

   amfi_code       date       nav
0     100016 2022-01-03  520.4608
1     100016 2022-01-04  515.0971
2     100016 2022-01-05  521.7239
3     100016 2022-01-06  515.7880
4     100016 2022-01-07  515.1639

In [117]:
print("Missing NAV values:")
print(nav_history["nav"].isnull().sum())

Missing NAV values:
0

In [118]:
before = len(nav_history)

nav_history = nav_history.drop_duplicates()

after = len(nav_history)

print(f"Duplicates Removed: {before - after}")

Duplicates Removed: 0

In [119]:
invalid_nav = nav_history[nav_history["nav"] <= 0]

print("Invalid NAV Records:", len(invalid_nav))

Invalid NAV Records: 0

In [120]:
nav_history.to_csv(
    PROCESSED_DATA / "nav_history_cleaned.csv",
    index=False
)

print("Saved Successfully!")

Saved Successfully!

### Observations - NAV History Dataset

- Successfully converted the date column to datetime format.
- Sorted the dataset by AMFI code and date.
- No missing NAV values were found.
- No duplicate records were detected.
- All NAV values were greater than zero.
- The cleaned dataset was saved to the processed data folder.

In [121]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [122]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [123]:
transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"]
)

print(transactions.dtypes)

investor_id                      str
transaction_date      datetime64[us]
amfi_code                      int64
transaction_type                 str
amount_inr                     int64
state                            str
city                             str
city_tier                        str
age_group                        str
gender                           str
annual_income_lakh           float64
payment_mode                     str
kyc_status                       str
dtype: object

In [124]:
print(transactions["transaction_type"].unique())

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [125]:
transactions["transaction_type"] = (
    transactions["transaction_type"]
    .str.strip()
    .str.title()
)

In [126]:
print(transactions["transaction_type"].unique())

<StringArray>
['Sip', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [127]:
invalid_amount = transactions[
    transactions["amount_inr"] <= 0
]

print("Invalid Amount Records:", len(invalid_amount))

Invalid Amount Records: 0

In [128]:
transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [129]:
before = len(transactions)

transactions = transactions.drop_duplicates()

after = len(transactions)

print("Duplicates Removed:", before - after)

Duplicates Removed: 0

In [130]:
transactions.columns.tolist()

['investor_id',
 'transaction_date',
 'amfi_code',
 'transaction_type',
 'amount_inr',
 'state',
 'city',
 'city_tier',
 'age_group',
 'gender',
 'annual_income_lakh',
 'payment_mode',
 'kyc_status']

In [131]:
print("KYC Status Values:")
print(transactions["kyc_status"].unique())

KYC Status Values:
<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [132]:
valid_kyc = ["Verified", "Pending"]

invalid_kyc = transactions[
    ~transactions["kyc_status"].isin(valid_kyc)
]

print("Invalid KYC Records:", len(invalid_kyc))

Invalid KYC Records: 0

In [133]:
transactions.to_csv(
    PROCESSED_DATA / "investor_transactions_cleaned.csv",
    index=False
)

print("Investor Transactions cleaned successfully!")

Investor Transactions cleaned successfully!

### Observations - Investor Transactions Dataset

- Converted transaction_date to datetime format.
- Standardized transaction type values.
- Verified all transaction amounts were greater than zero.
- No duplicate records were detected.
- KYC status values matched the expected categories.
- Saved the cleaned dataset to the processed folder.

In [134]:
performance.columns.tolist()

['amfi_code',
 'scheme_name',
 'fund_house',
 'category',
 'plan',
 'return_1yr_pct',
 'return_3yr_pct',
 'return_5yr_pct',
 'benchmark_3yr_pct',
 'alpha',
 'beta',
 'sharpe_ratio',
 'sortino_ratio',
 'std_dev_ann_pct',
 'max_drawdown_pct',
 'aum_crore',
 'expense_ratio_pct',
 'morningstar_rating',
 'risk_grade']

In [135]:
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [136]:
numeric_columns = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct",
    "benchmark_3yr_pct",
    "alpha",
    "beta",
    "sharpe_ratio",
    "sortino_ratio",
    "std_dev_ann_pct",
    "max_drawdown_pct",
    "aum_crore",
    "expense_ratio_pct",
    "morningstar_rating"
]

for col in numeric_columns:
    performance[col] = pd.to_numeric(performance[col], errors="coerce")

performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [137]:
performance[numeric_columns].isnull().sum()

return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
dtype: int64

In [138]:
invalid_expense = performance[
    (performance["expense_ratio_pct"] < 0.1) |
    (performance["expense_ratio_pct"] > 2.5)
]

print("Invalid Expense Ratio Records:", len(invalid_expense))

Invalid Expense Ratio Records: 0

In [139]:
return_columns = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct"
]

anomalies = performance[
    (performance[return_columns] < -100).any(axis=1) |
    (performance[return_columns] > 200).any(axis=1)
]

print("Anomalous Return Records:", len(anomalies))

Anomalous Return Records: 0

In [140]:
performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [141]:
before = len(performance)

performance = performance.drop_duplicates()

after = len(performance)

print("Duplicates Removed:", before - after)

Duplicates Removed: 0

In [142]:
performance.to_csv(
    PROCESSED_DATA / "scheme_performance_cleaned.csv",
    index=False
)

print("Scheme Performance cleaned successfully!")

Scheme Performance cleaned successfully!

### Observations - Scheme Performance Dataset

- Validated and converted all performance metrics to numeric data types.
- Checked for missing or invalid numeric values.
- Validated that expense ratios fall within the expected range (0.1%–2.5%).
- Checked for anomalous return values.
- No duplicate records were found.
- Saved the cleaned dataset to the processed folder.

In [143]:
fund_house = pd.read_csv(RAW_DATA / "aum_by_fund_house.csv")
fund_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [144]:
fund_house.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB

In [145]:
fund_house["date"] = pd.to_datetime(fund_house["date"])
fund_house.dtypes

date              datetime64[us]
fund_house                   str
aum_lakh_crore           float64
aum_crore                  int64
num_schemes                int64
dtype: object

In [146]:
fund_house.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [147]:
before = len(fund_house)

fund_house.drop_duplicates

after = len(fund_house)

print("Duplicates removed: ",before - after)

Duplicates removed:  0

In [148]:
fund_house.to_csv(
    PROCESSED_DATA / "aum_by_fund_house_cleaned.csv",
    index=False
)

print("aum by fun house cleaned successfully")

aum by fun house cleaned successfully

## Observations - AUM by Fund House Dataset

- Converted the date column to the appropriate `datetime` format.
- Verified that the dataset contains no missing values.
- No duplicate records were detected.
- The dataset was already well-structured and required minimal preprocessing.
- Saved the cleaned dataset to the processed folder.

In [149]:
benchmark = pd.read_csv(
    RAW_DATA / "benchmark_indices.csv"
)

benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [150]:
benchmark.info()

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   str
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: float64(1), str(2)
memory usage: 188.8 KB

In [151]:
benchmark["date"] = pd.to_datetime(benchmark["date"])
benchmark.dtypes

date           datetime64[us]
index_name                str
close_value           float64
dtype: object

In [152]:
benchmark.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [153]:
before = len(benchmark)

benchmark.drop_duplicates

after = len(benchmark)

print("Duplicates removed: ", before - after)

Duplicates removed:  0

In [154]:
benchmark.to_csv(
    PROCESSED_DATA / "benchmark_indices_cleaned.csv",
    index=False
)

## Observations - Benchmark Indices Dataset

- Converted the date column to the appropriate `datetime` format.
- Verified that all columns contained valid and consistent data types.
- Confirmed that there were no missing values in the dataset.
- No duplicate records were detected.
- Saved the cleaned dataset to the processed folder.

In [155]:
inflows = pd.read_csv(
    RAW_DATA / "category_inflows.csv"
)

inflows.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [156]:
inflows.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB

In [157]:
inflows["month"] = pd.to_datetime(inflows["month"])
inflows.dtypes

month               datetime64[us]
category                       str
net_inflow_crore           float64
dtype: object

In [158]:
inflows.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [159]:
before = len(inflows)

inflows.drop_duplicates

after = len(inflows)

print("Duplicates removed: ", before - after)

Duplicates removed:  0

In [160]:
inflows.to_csv(
    PROCESSED_DATA / "category_inflows_cleaned.csv",
    index=False
)

In [161]:
fund_master = pd.read_csv(
    RAW_DATA / "fund_master.csv"
)

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [162]:
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [163]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [164]:
before = len(fund_master)

fund_master.drop_duplicates

after = len(fund_master)

print("Duplicates removed: ", before - after)

Duplicates removed:  0

In [165]:
fund_master.to_csv(
    PROCESSED_DATA / "fund_master_cleaned.csv",
    index=False
)

In [166]:
folio_count = pd.read_csv(
    RAW_DATA / "industry_folio_count.csv"
)

folio_count.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [167]:
folio_count.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     str
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.1 KB

In [168]:
folio_count["month"] = pd.to_datetime(folio_count["month"])
folio_count.dtypes

month                  datetime64[us]
total_folios_crore            float64
equity_folios_crore           float64
debt_folios_crore             float64
hybrid_folios_crore           float64
others_folios_crore           float64
dtype: object

In [169]:
folio_count.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [170]:
before = len(folio_count)

folio_count.drop_duplicates

after = len(folio_count)

print("Duplicates removed: ", before - after)

Duplicates removed:  0

In [171]:
folio_count.to_csv(
    PROCESSED_DATA / "industry_folio_count_cleaned.csv",
    index=False
)

In [172]:
sip_inflows = pd.read_csv(
    RAW_DATA / "monthly_sip_inflows.csv"
)

sip_inflows.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [173]:
sip_inflows.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), str(1)
memory usage: 2.4 KB

In [174]:
sip_inflows["month"] = pd.to_datetime(sip_inflows["month"])
sip_inflows.dtypes

month                        datetime64[us]
sip_inflow_crore                      int64
active_sip_accounts_crore           float64
new_sip_accounts_lakh               float64
sip_aum_lakh_crore                  float64
yoy_growth_pct                      float64
dtype: object

In [175]:
sip_inflows.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [176]:
sip_inflows.loc[sip_inflows["yoy_growth_pct"].isnull(), ["month", "yoy_growth_pct"]]

        month  yoy_growth_pct
0  2022-01-01             NaN
1  2022-02-01             NaN
2  2022-03-01             NaN
3  2022-04-01             NaN
4  2022-05-01             NaN
5  2022-06-01             NaN
6  2022-07-01             NaN
7  2022-08-01             NaN
8  2022-09-01             NaN
9  2022-10-01             NaN
10 2022-11-01             NaN
11 2022-12-01             NaN

In [177]:
before = len(sip_inflows)

sip_inflows.drop_duplicates

after = len(sip_inflows)

print("Duplicates removed: ", before - after)

Duplicates removed:  0

In [178]:
sip_inflows.to_csv(
    PROCESSED_DATA / "monthly_sip_inflows_cleaned.csv",
    index=False
)

## Observations - Monthly SIP Inflows Dataset

- Converted the `month` column to the `datetime` format.
- Verified that all numeric columns were correctly typed.
- The `yoy_growth_pct` column contains 12 missing values, corresponding to the initial months where Year-over-Year growth cannot be calculated due to the absence of previous-year data.
- These missing values are expected and were retained without imputation.
- No duplicate records were detected.
- Saved the cleaned dataset to the `data/processed/` directory for further analysis.

In [179]:
holdings = pd.read_csv(
    RAW_DATA / "portfolio_holdings.csv"
)

holdings.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [180]:
holdings.info()

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB

In [181]:
holdings.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [182]:
before = len(holdings)

holdings.drop_duplicates

after = len(holdings)

print("Duplicates removed: ", before - after)

Duplicates removed:  0

In [183]:
holdings.to_csv(
    PROCESSED_DATA / "portfolio_holdings_cleaned.csv",
    index=False
)